/*
#389 Find the Difference

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.


*/

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */

 var findTheDifference = function(s, t) {
    
    const chars = new Array(26).fill(0);
    
    for(let i = 0; i < t.length; i++) {

        chars[t.charCodeAt(i) - 97]++;
    
        if(i < s.length) {
            chars[s.charCodeAt(i) - 97]--;
        }
    }
    
    
    for(let i = 0; i < chars.length; i++) {
        if(chars[i] > 0) return String.fromCharCode(i + 97);
    }
    
    return "";
};
